# Generated by Django 5.0.3 on 2025-04-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_profile_managers_remove_profile_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='historicalauto',
            name='profile',
        ),
    ]
