# Generated by Django 5.1.4 on 2025-05-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_auto_profile_remove_historicalauto_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalauto',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
