# Generated by Django 5.1.4 on 2025-05-24 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.profile'),
        ),
        migrations.AddField(
            model_name='historicalauto',
            name='profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cars.profile'),
        ),
    ]
