# Generated by Django 5.1.4 on 2025-05-25 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_profile_historicalauto_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='historicalauto',
            name='profile',
        ),
    ]
